// Dados fictícios para demonstração enquanto não há credenciais reais do Sponte

export const mockTurmas = [
  {
    TurmaID: 1001,
    Nome: "1º Ano A",
    Sigla: "1A",
    Situacao: 1,
    Turno: "Matutino",
    CursoID: 100,
    Curso: "Ensino Fundamental",
    AnoLetivo: 2026,
    DataInicio: "2026-02-01",
    DataTermino: "2026-12-15",
  },
  {
    TurmaID: 1002,
    Nome: "1º Ano B",
    Sigla: "1B",
    Situacao: 1,
    Turno: "Vespertino",
    CursoID: 100,
    Curso: "Ensino Fundamental",
    AnoLetivo: 2026,
    DataInicio: "2026-02-01",
    DataTermino: "2026-12-15",
  },
  {
    TurmaID: 1003,
    Nome: "2º Ano A",
    Sigla: "2A",
    Situacao: 1,
    Turno: "Matutino",
    CursoID: 100,
    Curso: "Ensino Fundamental",
    AnoLetivo: 2026,
    DataInicio: "2026-02-01",
    DataTermino: "2026-12-15",
  },
];

export const mockAlunos = [
  {
    AlunoID: 2001,
    Nome: "Ana Clara Santos",
    NumeroMatricula: "MAT001",
    RA: "RA001",
    Email: "ana.santos@coopen.com.br",
    TurmaAtual: "1º Ano A",
    Situacao: 1,
  },
  {
    AlunoID: 2002,
    Nome: "Bruno Oliveira Costa",
    NumeroMatricula: "MAT002",
    RA: "RA002",
    Email: "bruno.costa@coopen.com.br",
    TurmaAtual: "1º Ano A",
    Situacao: 1,
  },
  {
    AlunoID: 2003,
    Nome: "Camila Ferreira Pereira",
    NumeroMatricula: "MAT003",
    RA: "RA003",
    Email: "camila.pereira@coopen.com.br",
    TurmaAtual: "1º Ano A",
    Situacao: 1,
  },
  {
    AlunoID: 2004,
    Nome: "Daniel Marques Silva",
    NumeroMatricula: "MAT004",
    RA: "RA004",
    Email: "daniel.silva@coopen.com.br",
    TurmaAtual: "1º Ano B",
    Situacao: 1,
  },
  {
    AlunoID: 2005,
    Nome: "Eduarda Costa Gomes",
    NumeroMatricula: "MAT005",
    RA: "RA005",
    Email: "eduarda.gomes@coopen.com.br",
    TurmaAtual: "1º Ano B",
    Situacao: 1,
  },
  {
    AlunoID: 2006,
    Nome: "Felipe Rodrigues Alves",
    NumeroMatricula: "MAT006",
    RA: "RA006",
    Email: "felipe.alves@coopen.com.br",
    TurmaAtual: "1º Ano B",
    Situacao: 1,
  },
  {
    AlunoID: 2007,
    Nome: "Gabriela Nascimento Lima",
    NumeroMatricula: "MAT007",
    RA: "RA007",
    Email: "gabriela.lima@coopen.com.br",
    TurmaAtual: "2º Ano A",
    Situacao: 1,
  },
  {
    AlunoID: 2008,
    Nome: "Hugo Santos Barbosa",
    NumeroMatricula: "MAT008",
    RA: "RA008",
    Email: "hugo.barbosa@coopen.com.br",
    TurmaAtual: "2º Ano A",
    Situacao: 1,
  },
  {
    AlunoID: 2009,
    Nome: "Isabella Moreira Dias",
    NumeroMatricula: "MAT009",
    RA: "RA009",
    Email: "isabella.dias@coopen.com.br",
    TurmaAtual: "2º Ano A",
    Situacao: 1,
  },
  {
    AlunoID: 2010,
    Nome: "João Pedro Mendes",
    NumeroMatricula: "MAT010",
    RA: "RA010",
    Email: "joao.mendes@coopen.com.br",
    TurmaAtual: "1º Ano A",
    Situacao: 1,
  },
];

export const mockBoletins = [
  // Alunos 1º Ano A (turma 1001)
  {
    AlunoID: 2001,
    TurmaID: 1001,
    Frequencia: 95,
    ResultadoFinal: "Aprovado",
    ListaNotasBoletim: [
      {
        DisciplinaID: 3001,
        Disciplina: "Português",
        Nota1: 8.5,
        Nota2: 8.0,
        Nota3: 8.5,
        Nota4: 9.0,
        Media: 8.5,
        MediaFinal: 8.5,
        TotalFaltas: 2,
        PercentualFrequencia: 95,
        SituacaoDidatica: "Aprovado",
        Modulo: 1,
      },
      {
        DisciplinaID: 3002,
        Disciplina: "Matemática",
        Nota1: 7.5,
        Nota2: 7.0,
        Nota3: 7.5,
        Nota4: 8.0,
        Media: 7.5,
        MediaFinal: 7.5,
        TotalFaltas: 2,
        PercentualFrequencia: 95,
        SituacaoDidatica: "Aprovado",
        Modulo: 1,
      },
    ],
  },
  {
    AlunoID: 2002,
    TurmaID: 1001,
    Frequencia: 72,
    ResultadoFinal: "Risco",
    ListaNotasBoletim: [
      {
        DisciplinaID: 3001,
        Disciplina: "Português",
        Nota1: 4.5,
        Nota2: 5.0,
        Nota3: 4.8,
        Nota4: 5.2,
        Media: 4.9,
        MediaFinal: 4.9,
        TotalFaltas: 8,
        PercentualFrequencia: 72,
        SituacaoDidatica: "Recuperacao",
        Modulo: 1,
      },
      {
        DisciplinaID: 3002,
        Disciplina: "Matemática",
        Nota1: 5.0,
        Nota2: 5.5,
        Nota3: 5.2,
        Nota4: 5.8,
        Media: 5.4,
        MediaFinal: 5.4,
        TotalFaltas: 8,
        PercentualFrequencia: 72,
        SituacaoDidatica: "Recuperacao",
        Modulo: 1,
      },
    ],
  },
  {
    AlunoID: 2003,
    TurmaID: 1001,
    Frequencia: 88,
    ResultadoFinal: "Aprovado",
    ListaNotasBoletim: [
      {
        DisciplinaID: 3001,
        Disciplina: "Português",
        Nota1: 9.0,
        Nota2: 8.8,
        Nota3: 9.2,
        Nota4: 9.0,
        Media: 9.0,
        MediaFinal: 9.0,
        TotalFaltas: 3,
        PercentualFrequencia: 88,
        SituacaoDidatica: "Aprovado",
        Modulo: 1,
      },
      {
        DisciplinaID: 3002,
        Disciplina: "Matemática",
        Nota1: 8.5,
        Nota2: 8.2,
        Nota3: 8.8,
        Nota4: 8.5,
        Media: 8.5,
        MediaFinal: 8.5,
        TotalFaltas: 3,
        PercentualFrequencia: 88,
        SituacaoDidatica: "Aprovado",
        Modulo: 1,
      },
    ],
  },
  // Alunos 1º Ano B (turma 1002)
  {
    AlunoID: 2004,
    TurmaID: 1002,
    Frequencia: 85,
    ResultadoFinal: "Aprovado",
    ListaNotasBoletim: [
      {
        DisciplinaID: 3001,
        Disciplina: "Português",
        Nota1: 8.0,
        Nota2: 7.8,
        Nota3: 8.2,
        Nota4: 8.0,
        Media: 8.0,
        MediaFinal: 8.0,
        TotalFaltas: 4,
        PercentualFrequencia: 85,
        SituacaoDidatica: "Aprovado",
        Modulo: 1,
      },
    ],
  },
  {
    AlunoID: 2005,
    TurmaID: 1002,
    Frequencia: 70,
    ResultadoFinal: "Risco",
    ListaNotasBoletim: [
      {
        DisciplinaID: 3001,
        Disciplina: "Português",
        Nota1: 3.5,
        Nota2: 4.0,
        Nota3: 3.8,
        Nota4: 4.2,
        Media: 3.9,
        MediaFinal: 3.9,
        TotalFaltas: 9,
        PercentualFrequencia: 70,
        SituacaoDidatica: "Recuperacao",
        Modulo: 1,
      },
    ],
  },
  // 2º Ano A (turma 1003)
  {
    AlunoID: 2007,
    TurmaID: 1003,
    Frequencia: 92,
    ResultadoFinal: "Aprovado",
    ListaNotasBoletim: [
      {
        DisciplinaID: 3001,
        Disciplina: "Português",
        Nota1: 8.5,
        Nota2: 8.3,
        Nota3: 8.7,
        Nota4: 8.5,
        Media: 8.5,
        MediaFinal: 8.5,
        TotalFaltas: 2,
        PercentualFrequencia: 92,
        SituacaoDidatica: "Aprovado",
        Modulo: 1,
      },
    ],
  },
];

export const mockIntegrantes = [
  // Turma 1001
  { TurmaID: 1001, AlunoID: 2001, Nome: "Ana Clara Santos", NumeroChamada: 1 },
  { TurmaID: 1001, AlunoID: 2002, Nome: "Bruno Oliveira Costa", NumeroChamada: 2 },
  { TurmaID: 1001, AlunoID: 2003, Nome: "Camila Ferreira Pereira", NumeroChamada: 3 },
  { TurmaID: 1001, AlunoID: 2010, Nome: "João Pedro Mendes", NumeroChamada: 4 },

  // Turma 1002
  { TurmaID: 1002, AlunoID: 2004, Nome: "Daniel Marques Silva", NumeroChamada: 1 },
  { TurmaID: 1002, AlunoID: 2005, Nome: "Eduarda Costa Gomes", NumeroChamada: 2 },
  { TurmaID: 1002, AlunoID: 2006, Nome: "Felipe Rodrigues Alves", NumeroChamada: 3 },

  // Turma 1003
  { TurmaID: 1003, AlunoID: 2007, Nome: "Gabriela Nascimento Lima", NumeroChamada: 1 },
  { TurmaID: 1003, AlunoID: 2008, Nome: "Hugo Santos Barbosa", NumeroChamada: 2 },
  { TurmaID: 1003, AlunoID: 2009, Nome: "Isabella Moreira Dias", NumeroChamada: 3 },
];

export default {
  mockTurmas,
  mockAlunos,
  mockBoletins,
  mockIntegrantes,
};
